language: python
sudo: false
python:
 - "3.4"
 - "3.5"
 - "3.6"
env:
  global:
   - DRF="djangorestframework==3.8.1"
  matrix:
   - DJANGO="django==1.11.12"
   - DJANGO="django==2.0.4"
   - DJANGO="django==2.0.4" LINT=1
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO $DRF
 - pip install flake8 psycopg2-binary
script:
 - ./runtests.sh
addons:
  postgresql: "9.6"
  apt:
    packages:
     - postgresql-9.6-postgis-2.3
